import './globals.css';
import { Inter } from 'next/font/google';
import { Header, Alert } from '@/components';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Alert message={'Hello '} />
				<Header />
				{children}
			</body>
		</html>
	);
}
